POSTURE_ROUTINE = {
    "p1": {"name": "Apertura de pecho en marco de puerta", "detail": "30s × 2"},
    "p2": {"name": "Chin tuck doble mentón", "detail": "10 reps × 2"},
    "p3": {"name": "Rotación torácica en suelo", "detail": "8 reps × lado"},
    "p4": {"name": "Apertura de hombros con banda o toalla", "detail": "15 reps"},
    "p5": {"name": "Estiramiento de flexores de cadera media luna", "detail": "45s × lado"},
}

WEEK_PLAN = {
    "lunes": {
        "name": "Lunes",
        "tag": "EMPUJE",
        "accent": "#2980B9",
        "warmup": "5 min bicicleta moderada + 2 series livianas de press",
        "cardio": "10 min bicicleta estática",
        "ankle": "✓ Carga nula en tobillo.",
        "exercises": {
            "l1": {"name": "Face pull en polea (cuerda)", "detail": "3×15–20 | 60s", "postura": True},
            "l2": {"name": "Press de banca plana (barra)", "detail": "4×10–12 | 90s"},
            "l3": {"name": "Press inclinado con mancuernas", "detail": "3×10–12 | 75s"},
            "l4": {"name": "Press militar en máquina", "detail": "3×10–12 | 75s"},
            "l5": {"name": "Elevaciones laterales", "detail": "3×12–15 | 60s"},
            "l6": {"name": "Extensión de tríceps en polea (cuerda)", "detail": "3×12–15 | 60s"},
        },
    },
    "martes": {
        "name": "Martes",
        "tag": "JALE",
        "accent": "#27AE60",
        "warmup": "5 min remo suave + rotaciones de hombro",
        "cardio": "10 min elíptica",
        "ankle": "✓ Todo sentado o de pie con apoyo.",
        "exercises": {
            "ma1": {"name": "Jalón al pecho en polea agarre ancho", "detail": "4×10–12 | 90s"},
            "ma2": {"name": "Remo en polea baja un brazo a la vez", "detail": "3×10–12 c/lado | 75s"},
            "ma3": {"name": "Remo en máquina sentado agarre neutro", "detail": "3×10–12 | 75s"},
            "ma4": {"name": "Jalón agarre supino", "detail": "3×10–12 | 75s", "postura": True},
            "ma5": {"name": "Curl en polea baja con barra", "detail": "3×10–12 | 60s"},
            "ma6": {"name": "Curl en polea baja con cuerda martillo", "detail": "3×12 | 60s"},
        },
    },
    "miercoles": {
        "name": "Miércoles",
        "tag": "DESCANSO ACTIVO",
        "accent": "#F39C12",
        "warmup": None,
        "cardio": None,
        "ankle": None,
        "exercises": {
            "mi1": {"name": "Foam rolling columna torácica", "detail": "2 min", "postura": True},
            "mi2": {"name": "Extensión torácica sobre el rodillo", "detail": "5 reps × zona", "postura": True},
            "mi3": {"name": "Estiramiento cadena posterior", "detail": "2 min c/lado"},
            "mi4": {"name": "Movilidad de cadera paloma modificada", "detail": "90s c/lado"},
            "mi5": {"name": "Cat-cow + rotación torácica", "detail": "10 reps"},
        },
    },
    "jueves": {
        "name": "Jueves",
        "tag": "PIERNAS",
        "accent": "#8E44AD",
        "warmup": "5 min bicicleta suave + movilidad tobillo en círculos + activación glúteo con banda",
        "cardio": "10 min bicicleta estática",
        "ankle": "⚠️ Sin squat libre ni zancadas. Ejercicios de tobillo al final.",
        "exercises": {
            "j1": {"name": "Prensa de piernas máquina", "detail": "4×12–15 | 90s"},
            "j2": {"name": "Extensión de cuádriceps máquina", "detail": "3×12–15 | 60s"},
            "j3": {"name": "Curl femoral tumbado máquina", "detail": "3×12–15 | 60s"},
            "j4": {"name": "Hip thrust con barra o mancuerna", "detail": "4×12–15 | 90s", "postura": True},
            "j5": {"name": "Abducción en máquina", "detail": "3×15–20 | 60s"},
            "j6": {"name": "🦶 Eversión con banda elástica sentado", "detail": "3×15–20 | 45s", "ankle": "PERONEO"},
            "j7": {"name": "🦶 Inversión con banda elástica sentado", "detail": "3×15 | 45s", "ankle": "PERONEO"},
            "j8": {"name": "🦶 Excéntrico de pantorrilla en escalón (Alfredson)", "detail": "3×15 | 60s", "ankle": "AQUILES"},
            "j9": {"name": "🦶 Estiramiento de sóleo rodilla flexionada", "detail": "45s×3×lado", "ankle": "AQUILES"},
            "j10": {"name": "🦶 Movilidad tobillo knee-to-wall", "detail": "10 reps c/lado", "ankle": "PERONEO"},
        },
    },
    "viernes": {
        "name": "Viernes",
        "tag": "CORE + CARDIO",
        "accent": "#C0392B",
        "warmup": "3 min bicicleta + activación abdominal suave",
        "cardio": "20 min bicicleta o elíptica con intervalos suaves",
        "ankle": "✓ Sin saltos ni impacto.",
        "exercises": {
            "v1": {"name": "Plancha frontal", "detail": "3×30–45s | 45s", "postura": True},
            "v2": {"name": "Plancha lateral", "detail": "3×20–30s c/lado | 45s"},
            "v3": {"name": "Crunch en máquina", "detail": "3×15–20 | 60s"},
            "v4": {"name": "Superman en suelo", "detail": "3×12–15 | 45s", "postura": True},
            "v5": {"name": "Bird-dog", "detail": "3×10 c/lado | 45s", "postura": True},
            "v6": {"name": "Pallof press polea", "detail": "3×12 c/lado | 60s"},
        },
    },
    "sabado": {
        "name": "Sábado",
        "tag": "FULL BODY LIGERO",
        "accent": "#1A5276",
        "warmup": "5 min caminata + movilidad articular completa",
        "cardio": "15 min elíptica ritmo suave",
        "ankle": "✓ Rehabilitación tobillo al final.",
        "exercises": {
            "s1": {"name": "Remo en máquina sentado", "detail": "3×12 | 75s"},
            "s2": {"name": "Press de mancuernas banco plano", "detail": "3×12 | 75s"},
            "s3": {"name": "Prensa de piernas peso ligero", "detail": "3×15 | 60s"},
            "s4": {"name": "Y-T-W en banco inclinado", "detail": "3×10 c/forma | 60s", "postura": True},
            "s5": {"name": "Curl con mancuernas excéntrico", "detail": "3×12 | 60s"},
            "s6": {"name": "Plancha", "detail": "2×30s | 45s"},
            "s7": {"name": "🦶 Eversión con banda elástica sentado", "detail": "3×15–20 | 45s", "ankle": "PERONEO"},
            "s8": {"name": "🦶 Excéntrico de pantorrilla en escalón", "detail": "3×15 | 60s", "ankle": "AQUILES"},
            "s9": {"name": "🦶 Estiramiento de sóleo rodilla flexionada", "detail": "45s×3×lado", "ankle": "AQUILES"},
        },
    },
    "domingo": {
        "name": "Domingo",
        "tag": "CICLOVÍA",
        "accent": "#1E8449",
        "warmup": None,
        "cardio": "La salida misma es el cardio",
        "ankle": "⚠️ Terreno plano. Si hay dolor, camina solamente.",
        "exercises": {
            "d1": {"name": "Caminata + trote suave ciclovía", "detail": "30–60 min"},
            "d2": {"name": "Estiramiento post-salida", "detail": "5–10 min"},
        },
    },
}

DAY_ORDER = ["lunes", "martes", "miercoles", "jueves", "viernes", "sabado", "domingo"]

WEEKDAY_TO_KEY = {
    0: "lunes",
    1: "martes",
    2: "miercoles",
    3: "jueves",
    4: "viernes",
    5: "sabado",
    6: "domingo",
}
