[theme]
base = "light"
primaryColor     = "#B0392A"
backgroundColor  = "#ECDEC2"
secondaryBackgroundColor = "#F5EBD3"
textColor        = "#2A1C10"
font             = "sans serif"

[server]
headless = true
